apiVersion: v1
kind: Service
metadata:
  name: configtest-service
spec:
  selector:
    app: configtest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort
